// Ordered presets: keep the first six keys compatible with the original shortcut.
export const EMOTION_VARIANTS = Object.freeze([
  { key: "happy", description: "happy, bright smiling expression", emoji: "😊" },
  { key: "sad", description: "sad, downcast eyes and a small trembling frown", emoji: "😢" },
  { key: "wow", description: "surprised, wide eyes and an open-mouth wow expression", emoji: "😮" },
  { key: "love", description: "loving, affectionate expression with small floating hearts", emoji: "😍" },
  { key: "angry", description: "angry, furrowed brows and a clenched frustrated expression", emoji: "😡" },
  { key: "wink", description: "playful winking expression with one eye closed and a cheeky smile", emoji: "😉" },
  { key: "laugh", description: "laughing hard, eyes squeezed shut and a wide joyful grin", emoji: "😂" },
  { key: "cry", description: "sobbing openly, streaming tears and a visibly distressed face", emoji: "😭" },
  { key: "shy", description: "shy, soft blush, a timid smile and bashfully averted eyes", emoji: "☺️" },
  { key: "thinking", description: "thoughtful, hand at chin and eyes looking upward in contemplation", emoji: "🤔" },
  { key: "confused", description: "confused, uneven raised eyebrows and a puzzled tilted head", emoji: "😕" },
  { key: "scared", description: "frightened, wide alarmed eyes and a tense recoiling posture", emoji: "😨" },
  { key: "tired", description: "exhausted, drooping eyelids, slumped shoulders and a weary expression", emoji: "😩" },
  { key: "sleepy", description: "sleepy, eyes nearly closed with a gentle yawn", emoji: "😴" },
  { key: "cool", description: "cool and relaxed, confident easy smile and a casual laid-back pose", emoji: "😎" },
  { key: "party", description: "celebrating, enthusiastic raised arms and a joyful expression with small confetti", emoji: "🥳" },
  { key: "grateful", description: "grateful, warm appreciative smile and hands held together in thanks", emoji: "🙏" },
  { key: "proud", description: "proud of an achievement, chin lifted and a satisfied self-assured smile", emoji: "😌" },
  { key: "pleading", description: "pleading, large puppy eyes and a small hopeful pout", emoji: "🥺" },
  { key: "bored", description: "bored, flat half-lidded stare and cheek resting on one hand", emoji: "😑" },
  { key: "disgusted", description: "disgusted, wrinkled nose and a visibly repulsed expression", emoji: "🤢" },
  { key: "embarrassed", description: "embarrassed, flushed cheeks and an awkward nervous smile", emoji: "😳" },
  { key: "hopeful", description: "hopeful, eager eyes and fingers crossed in anticipation", emoji: "🤞" },
  { key: "relieved", description: "relieved, eyes gently closed while releasing a relaxed sigh", emoji: "😮‍💨" },
  { key: "determined", description: "determined, focused eyes, firm jaw and a resolute forward stance", emoji: "💪" },
  { key: "suspicious", description: "suspicious, narrowed eyes and one eyebrow raised in skeptical scrutiny", emoji: "🤨" },
  { key: "jealous", description: "jealous, resentful sideways glance and a tight envious pout", emoji: "😒" },
  { key: "lonely", description: "lonely, wistful faraway gaze and a quiet withdrawn posture", emoji: "🥲" },
  { key: "nervous", description: "nervous, uneasy smile, tense posture and a small sweat drop", emoji: "😅" },
  { key: "curious", description: "curious, attentive bright eyes and a head leaning forward to investigate", emoji: "🧐" },
  { key: "impressed", description: "impressed, admiring raised eyebrows and an appreciative amazed smile", emoji: "🤩" },
  { key: "apologetic", description: "apologetic, remorseful lowered gaze and hands raised in a gentle apology", emoji: "🙇" },
  { key: "frustrated", description: "frustrated, scrunched face and hands pressed against the temples", emoji: "😤" },
  { key: "peaceful", description: "peaceful, serene closed eyes and an untroubled gentle smile", emoji: "🧘" },
  { key: "mischievous", description: "mischievous, sly sideways smile and a teasing secretive expression", emoji: "😏" },
  { key: "overwhelmed", description: "overwhelmed, spiraling unfocused eyes and a frazzled expression", emoji: "😵‍💫" },
].map((emotion) => Object.freeze(emotion)));
