-- Private, append-only account activity used by the authenticated history API.
create table if not exists public.account_activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  event_type text not null check (
    event_type in ('generation', 'spend', 'topup', 'refund', 'reward', 'subscription', 'adjustment')
  ),
  delta integer not null default 0,
  balance_after integer,
  description text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists account_activity_user_created_idx
  on public.account_activity (user_id, created_at desc, id desc);

alter table public.account_activity enable row level security;
revoke all on table public.account_activity from anon, authenticated;
grant select, insert on table public.account_activity to service_role;
grant usage, select on sequence public.account_activity_id_seq to service_role;
